version: "3"

services:
  calendar:
    build:
      context: ./front
      args:
        API_CITY: ${API_CITY}
        API_KEY: ${API_KEY}
    container_name: calendar
    command: serve -s build -l 32041
    ports:
      - "32041:32041"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    # before run cmd:  docker network create dock-vv-network
    networks:
      - v1-network

networks:
  v1-network:
    external: true
